### ISSUE TITLE
安装SDK后收不到任何上报信息

### ISSUE THREAD

**Issue by wujunze** [youzan/raven-weapp#10]
你好
安装SDK后收不到任何上报信息
帮忙看看  谢谢

**Comment by baofengs** [comment]
可以看一下源码 *src/raven.js* 的第 1888 行
```
    if (this._globalOptions.environment === 'production') {
      wx.request({
        url: opts.url + '?' + urlencode(opts.auth),
        method: 'POST',
        header: {
          'content-type': 'text/plain;charset=UTF-8'
        },
        data: stringify(opts.data),
        success: function() {
          opts.onSuccess && opts.onSuccess();
        },
        fail: function(err) {
          opts.onError && opts.onError(err);
        }
      });
    }
```

所以，你应该在代码中指定 `environment `

```
options = {
    environment: '指定为production才会上报'
}
```

**Comment by wujunze** [comment]
已经指定 environment为production 还是没有上报信息  
会自动上报console.log信息吗   还是需要手动触发  @x-bao

**Comment by baofengs** [comment]
`console.log` 的内容会自动捕捉，然后放到这个位置（见下图）
![image](https://user-images.githubusercontent.com/34507012/49784945-d0b15780-fd59-11e8-8a34-1d253095d4e8.png)

你也可以使用`sentry`的相关 API 手动触发：
- Raven.captureMessage(msg, option)
- Raven.captureBreadcrumb

详情参考 `sentry` 的官方文档。

**Comment by baofengs** [comment]
准确的说是：触发`Raven.captureMessage(msg, option)` 之后，才会把页面中的 `console.log` 相关的信息给捕获 & 打印来。如果你只是 `console.log`，在 sentry 里边是收不到任何消息的

**Comment by wujunze** [comment]
我在app.js里面 这样测试的  还是收不到上报的信息    请你帮忙看看 谢谢
```js
import appname from './common/appname.js'
let services = require('./services/services.js');
var Raven = require('./raven/raven.min.js')

Raven.config('http://e017f70052c6474db1f7ee0f76273014@sentry.xxxx.com/7', options).install()
var msg = 'test';
Raven.captureMessage(msg) 
App({
  globalData: {
    userInfo: null,
    class_id:null,  //保存当前选择的编辑类型
    counselor_user_id:'', //在顾问端时存储用户id 用于查找优惠券与兑换优惠券
  },
  onLaunch: function () {
    wx.login({
      success: function (res) {
        if (res.code) {
          // //发起网络请求
          services.request({
            url: 'services/auth/mini_program/deJsCode',
            method: 'POST',
            data: {
              code: res.code,
              appname: appname,
            },
          }).then((res) => {
            if (res.code === 0) {
              wx.setStorage({
                key: "wxLoginKey",
                data: res.wx_login_key,
              })
            }
          })

          
        } else {
          console.log('登录失败！' + res.errMsg)
        }
      }
      

    });
  
  },
})


```

**Comment by baofengs** [comment]
看上一条回复。
还是不行就先把 sentry 的文档看一遍吧。先把 web 的搞清楚，然后再来看小程序的。

**Comment by baofengs** [comment]
看上一条回复。
还是不行就先把 sentry 的文档看一遍吧。先把 web 的搞清楚，然后再来看小程序的。

**Comment by wujunze** [comment]
@x-bao   已经用了很久时间的Web版了    都正常 
小程序这个收不到上报信息   你怎么配置的  帮忙看看

**Comment by baofengs** [comment]
文档怎么写，我就是怎么做的。多试试

**Comment by wujunze** [comment]
OK  你那边使用正常?  @x-bao

**Comment by baofengs** [comment]
一切正常，做了一点小优化。提了 pull request，但是没有人理...

**Comment by qinghua5453** [comment]
> 可以看一下源码 _src/raven.js_ 的第 1888 行
> 
> ```
>     if (this._globalOptions.environment === 'production') {
>       wx.request({
>         url: opts.url + '?' + urlencode(opts.auth),
>         method: 'POST',
>         header: {
>           'content-type': 'text/plain;charset=UTF-8'
>         },
>         data: stringify(opts.data),
>         success: function() {
>           opts.onSuccess && opts.onSuccess();
>         },
>         fail: function(err) {
>           opts.onError && opts.onError(err);
>         }
>       });
>     }
> ```
> 所以，你应该在代码中指定 `environment `
> 
> ```
> options = {
>     environment: '指定为production才会上报'
> }
> ```
请问您小程序有用什么开源的框架吗？
我用的mpvue，正常引入npm run dev 或者 npm run build 均报错

**Comment by qinghua5453** [comment]
> 一切正常，做了一点小优化。提了 pull request，但是没有人理...

执行npm run dev 出现这个报错
This relative module was not found:

* ../utils/raven-weapp/build/raven.min.js in ./node_modules/mpvue-entry/dist/cardReserve.js, ./node_modules/mpvue-entry/dist/demoSlide.js and 32 others

**Comment by qinghua5453** [comment]
> 已经指定 environment为production 还是没有上报信息
> 会自动上报console.log信息吗 还是需要手动触发 @x-bao

请问你最后是捕获到了吗？

**Comment by wujunze** [comment]
没有捕获到

**Comment by wujunze** [comment]
已经解决了

**Comment by wujunze** [comment]
Thanks @qinghua5453
